[book]
authors = ["parasaurolophus"]
language = "en"
multilingual = false
src = "src"
title = "Kirk Rader"

[preprocessor]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
mathjax-support = true
preferred-dark-theme = "coal"
prefers-color-scheme = "dark"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
